Repository prathimacode-hub/PyAlgo-Tree, pull requests merged in 2021-07, with the labels that each got.

#10 Added bubble sort in sorting folder.
  Sorting/Bubble Sort/Images/Demo.txt
  Sorting/Bubble Sort/Images/output.jpg
  Sorting/Bubble Sort/README.md
  Sorting/Bubble Sort/bubble_sort.py
Labels: DCP21, 🟩 Level1

#14 Added selection sort
  Sorting/Selection Sort/Images/output.jpg
  Sorting/Selection Sort/README.md
  Sorting/Selection Sort/selection_sort.py
Labels: DCP21, 🟩 Level1

#17 Water Jug Problem
  Backtracking/README.md
  Backtracking/Water Jug Problem/Images/ss1.png
  Backtracking/Water Jug Problem/Images/ss2.png
  Backtracking/Water Jug Problem/Images/ss3.png
  Backtracking/Water Jug Problem/Images/ss4.png
  Backtracking/Water Jug Problem/README.md
  Backtracking/Water Jug Problem/water_jug_problem.py
Labels: DCP21, 🟨 Level2

#21 Determining DNA Health
  Strings/Determining DNA Health/Determining_DNA_Health.py
  Strings/Determining DNA Health/Images/dna1.png
  Strings/Determining DNA Health/Images/dna2.png
  Strings/Determining DNA Health/Images/dna3.png
  Strings/Determining DNA Health/Images/dna4.png
  Strings/Determining DNA Health/Images/dna5.png
  Strings/Determining DNA Health/README.md
Labels: DCP21, 🟧 Level3

#22 binary search
  Searching/Binary Search/Images/output.jpg
  Searching/Binary Search/README.md
  Searching/Binary Search/binary_search.py
Labels: DCP21, 🟩 Level1

#20 Added Heap Sort
  Sorting/Heap Sort/Images/heap_sort.png
  Sorting/Heap Sort/README.md
  Sorting/Heap Sort/heap_sort.py
Labels: DCP21, 🟩 Level1

#26 Sudoku Solver #18 added
  Backtracking/Sudoku Solver/Images/output.png
  Backtracking/Sudoku Solver/Images/output_error.png
  Backtracking/Sudoku Solver/Images/sample.png
  Backtracking/Sudoku Solver/README.md
  Backtracking/Sudoku Solver/sudoku.py
Labels: DCP21, 🟨 Level2

#25 Predicting House Prices
  Machine Learning/Predicting House Prices/Images/lin1.png
  Machine Learning/Predicting House Prices/Images/lin2.png
  Machine Learning/Predicting House Prices/Images/lin3.png
  Machine Learning/Predicting House Prices/Images/lin4.png
  Machine Learning/Predicting House Prices/Images/lin5.png
  Machine Learning/Predicting House Prices/Images/lin6.png
  Machine Learning/Predicting House Prices/Predicting_House_Prices.py
  Machine Learning/Predicting House Prices/README.md
  Machine Learning/Predicting House Prices/requirements.txt
Labels: DCP21, 🟧 Level3

#30 Find Angle MBC
  Geometry/Find Angle MBC/Find_Angle_MBC.py
  Geometry/Find Angle MBC/Images/mbc1.png
  Geometry/Find Angle MBC/Images/mbc2.png
  Geometry/Find Angle MBC/Images/mbc3.png
  Geometry/Find Angle MBC/Images/mbc4.png
  Geometry/Find Angle MBC/Images/mbc5.png
  Geometry/Find Angle MBC/Images/mbc6.png
  Geometry/Find Angle MBC/README.md
Labels: DCP21, 🟨 Level2

#32 Added linear search
  Searching/Linear Search/Images/output.jpg
  Searching/Linear Search/README.md
  Searching/Linear Search/linear_search.py
Labels: DCP21, 🟩 Level1

#35 Tic Tac Toe Game
  Backtracking/README.md
  Backtracking/Tic Tac Toe Game/Images/ss1.png
  Backtracking/Tic Tac Toe Game/Images/ss2.png
  Backtracking/Tic Tac Toe Game/README.md
  Backtracking/Tic Tac Toe Game/tic_tac_toe_game.py
Labels: DCP21, 🟧 Level3

#46 Palindrome Check with Recursion
  Recursion/Palindrome Check/Images/Palindrome_Check_1.PNG
  Recursion/Palindrome Check/Images/Palindrome_Check_2.PNG
  Recursion/Palindrome Check/Images/Palindrome_Check_3.PNG
  Recursion/Palindrome Check/Images/Palindrome_Check_4.PNG
  Recursion/Palindrome Check/README.md
  Recursion/Palindrome Check/palindrome_check.py
  Recursion/README.md
Labels: DCP21, 🟩 Level1

#44 Caesar_Cipher
  Cryptography/Caesar Cipher/Images/DecryptedString.png
  Cryptography/Caesar Cipher/Images/EncryptedStringOutput.png
  Cryptography/Caesar Cipher/Images/README.md
  Cryptography/Caesar Cipher/README.md
  Cryptography/Caesar Cipher/caesar_cipher.py
  Cryptography/README.md
Labels: DCP21, 🟩 Level1

#39 N Queens
  Backtracking/N Queens/Images/ss.png
  Backtracking/N Queens/README.md
  Backtracking/N Queens/n_queens.py
  Backtracking/README.md
Labels: DCP21, 🟩 Level1

#50 Knight's Tour
  Backtracking/Knight's Tour/Images/ss.png
  Backtracking/Knight's Tour/README.md
  Backtracking/Knight's Tour/knight's_tour.py
  Backtracking/README.md
Labels: DCP21, 🟨 Level2

#49 Transposition Cipher
  Cryptography/README.md
  Cryptography/Transposition Cipher/Images/Output1.PNG
  Cryptography/Transposition Cipher/README.md
  Cryptography/Transposition Cipher/transposition_cipher.py
Labels: DCP21, 🟩 Level1

#51 Hamiltonian Cycle
  Backtracking/Hamiltonian Cycle/Images/ss.png
  Backtracking/Hamiltonian Cycle/README.md
  Backtracking/Hamiltonian Cycle/hamiltonian_cycle.py
  Backtracking/README.md
Labels: DCP21, 🟨 Level2

#59 Cryptarithmetic Problem
  Backtracking/Cryptarithmetic Problem/Images/ss.png
  Backtracking/Cryptarithmetic Problem/README.md
  Backtracking/Cryptarithmetic Problem/cryptarithmetic_problem.py
  Backtracking/README.md
Labels: DCP21, 🟨 Level2

#47 Singly Linked List (#31)
  Lists/Singly Linked List/Images/Screenshot_1.png
  Lists/Singly Linked List/README.md
  Lists/Singly Linked List/singly_linked_list.py
Labels: DCP21, 🟧 Level3

#56 Expression tree evaluation
  Trees/Expression Tree Evaluation/Images/expression_tree_evaluation_output.PNG
  Trees/Expression Tree Evaluation/Images/expression_tree_evaluation_output2.PNG
  Trees/Expression Tree Evaluation/README.md
  Trees/Expression Tree Evaluation/expression_tree_evaluation.py
  Trees/README.md
Labels: DCP21, 🟨 Level2

#61 Graph Coloring Problem
  Backtracking/Graph Coloring Problem/Images/ss.png
  Backtracking/Graph Coloring Problem/README.md
  Backtracking/Graph Coloring Problem/graph_coloring_problem.py
  Backtracking/README.md
Labels: DCP21, 🟨 Level2

#64 Subset Sum
  Backtracking/README.md
  Backtracking/Subset Sum/Images/ss.png
  Backtracking/Subset Sum/README.md
  Backtracking/Subset Sum/subset_sum.py
Labels: DCP21, 🟩 Level1

#66 Infix to postfix conversion
  Stacks/Infix to Postfix Conversion/Images/infix_to_postfix_conversion1.PNG
  Stacks/Infix to Postfix Conversion/Images/infix_to_postfix_conversion2.PNG
  Stacks/Infix to Postfix Conversion/Images/infix_to_postfix_conversion3.PNG
  Stacks/Infix to Postfix Conversion/README.md
  Stacks/Infix to Postfix Conversion/infix_to_postfix_conversion.py
  Stacks/README.md
Labels: DCP21, 🟨 Level2

#69 8 Puzzle Problem using A star Algorithm
  Artificial Intelligence/8 Puzzle Problem using A star Algorithm/8_puzzle_problem_using_A_star_algorithm.py
  Artificial Intelligence/8 Puzzle Problem using A star Algorithm/Images/ss.png
  Artificial Intelligence/8 Puzzle Problem using A star Algorithm/README.md
  Artificial Intelligence/README.md
Labels: DCP21, 🟧 Level3

#75 8 Puzzle Problem using BFS
  Artificial Intelligence/8 Puzzle Problem using BFS/8_puzzle_problem_using_BFS.py
  Artificial Intelligence/8 Puzzle Problem using BFS/Images/ss1.png
  Artificial Intelligence/8 Puzzle Problem using BFS/Images/ss2.png
  Artificial Intelligence/8 Puzzle Problem using BFS/Images/ss3.png
  Artificial Intelligence/8 Puzzle Problem using BFS/Images/ss4.png
  Artificial Intelligence/8 Puzzle Problem using BFS/README.md
  Artificial Intelligence/README.md
Labels: DCP21, 🟧 Level3

#76 Segment Tree Creation
  Trees/README.md
  Trees/Segment Tree Creation/Images/creation_output1.PNG
  Trees/Segment Tree Creation/Images/creation_output2.PNG
  Trees/Segment Tree Creation/Images/creation_output3.PNG
  Trees/Segment Tree Creation/README.md
  Trees/Segment Tree Creation/segment_tree_creation.py
Labels: DCP21, 🟨 Level2

#74 Added Shell Sort
  Sorting/Shell Sort/Images/shell_sort.png
  Sorting/Shell Sort/README.md
  Sorting/Shell Sort/shell_sort.py
Labels: DCP21, 🟩 Level1

#78 Segment tree update query
  Trees/README.md
  Trees/Segment Tree Update Query/Images/update_query_output1.PNG
  Trees/Segment Tree Update Query/Images/update_query_output2.PNG
  Trees/Segment Tree Update Query/README.md
  Trees/Segment Tree Update Query/segment_tree_update_query.py
Labels: DCP21, 🟨 Level2

#80 Segment tree range sum query
  Trees/README.md
  Trees/Segment Tree Range Sum Query/Images/range_sum_query_output1.PNG
  Trees/Segment Tree Range Sum Query/Images/range_sum_query_output2.PNG
  Trees/Segment Tree Range Sum Query/README.md
  Trees/Segment Tree Range Sum Query/segment_tree_sum_range_query.py
Labels: DCP21, 🟨 Level2

#86 Binary tree to dll
  Trees/Binary Tree To DLL/Images/binary_tree_to_dll_output1.PNG
  Trees/Binary Tree To DLL/Images/binary_tree_to_dll_output2.PNG
  Trees/Binary Tree To DLL/Images/binary_tree_to_dll_output3.PNG
  Trees/Binary Tree To DLL/README.md
  Trees/Binary Tree To DLL/binary_tree_to_dll.py
Labels: DCP21, 🟨 Level2

#90 Average Calculator
  Maths/Average Calculator/Images/ss.png
  Maths/Average Calculator/README.md
  Maths/Average Calculator/average_calculator.py
  Maths/README.md
Labels: DCP21, 🟪 Level0

#88 Fibonacci
  Recursion/Fibonacci/Images/output.png
  Recursion/Fibonacci/README.md
  Recursion/Fibonacci/fib.py
Labels: DCP21, 🟪 Level0

#85 All indices of an element in an array.
  Recursion/All indices/All_indices.py
  Recursion/All indices/Images/Output-img.jpg
  Recursion/All indices/README.md
Labels: DCP21, 🟩 Level1

#87 Insertion Sort
  Sorting/Insertion Sort/Images/input.png
  Sorting/Insertion Sort/Images/sort_output1.png
  Sorting/Insertion Sort/README.md
  Sorting/Insertion Sort/insertion_sort.py
Labels: DCP21, To Do, 🟩 Level1

#94 Bad String
  Strings/Bad String/Images/ss.png
  Strings/Bad String/README.md
  Strings/Bad String/bad_string.py
  Strings/README.md
Labels: DCP21, To Do, 🟪 Level0

#99 Lowest common ancestor Binary tree
  Trees/Lowest Common Ancestor Binary Tree/Images/README.md
  Trees/Lowest Common Ancestor Binary Tree/Images/lowest_common_ancestor_binary_tree_output1.PNG
  Trees/Lowest Common Ancestor Binary Tree/Images/lowest_common_ancestor_binary_tree_output2.PNG
  Trees/Lowest Common Ancestor Binary Tree/Images/lowest_common_ancestor_binary_tree_output3.PNG
  Trees/Lowest Common Ancestor Binary Tree/Images/lowest_common_ancestor_binary_tree_output4.PNG
  Trees/Lowest Common Ancestor Binary Tree/README.md
  Trees/Lowest Common Ancestor Binary Tree/lowest_common_ancestor_binary_tree.py
  Trees/README.md
Labels: DCP21, To Do, 🟨 Level2

#96 Merge sort Algorithm
  Sorting/Merge Sort/Images/output.png
  Sorting/Merge Sort/README.md
  Sorting/Merge Sort/merge_sort.py
Labels: DCP21, To Do, 🟩 Level1

#98 Reverse Cipher
  Cryptography/README.md
  Cryptography/Reverse Cipher/Images/reverse_cipher.png
  Cryptography/Reverse Cipher/README.md
  Cryptography/Reverse Cipher/reverse_cipher.py
Labels: DCP21, To Do, 🟪 Level0

#27 BST added
  Trees/Binary Search Tree/BST.py
  Trees/Binary Search Tree/Images/output1.png
  Trees/Binary Search Tree/Images/output2.png
  Trees/Binary Search Tree/Images/output3.png
  Trees/Binary Search Tree/Images/output4.png
  Trees/Binary Search Tree/Images/output5.png
  Trees/Binary Search Tree/README.md
Labels: DCP21, To Do, 🟨 Level2

#102 Lowest common ancestor in binary search tree
  Trees/Lowest Common Ancestor Binary Search Tree/Images/lowest_common_ancestor_binary_search_tree_output1.PNG
  Trees/Lowest Common Ancestor Binary Search Tree/Images/lowest_common_ancestor_binary_search_tree_output2.PNG
  Trees/Lowest Common Ancestor Binary Search Tree/Images/lowest_common_ancestor_binary_search_tree_output3.PNG
  Trees/Lowest Common Ancestor Binary Search Tree/README.md
  Trees/Lowest Common Ancestor Binary Search Tree/lowest_common_ancestor_binary_search_tree.py
  Trees/README.md
Labels: DCP21, To Do, 🟨 Level2

#103 Doubly linked list
  Lists/Doubly Linked List/Images/Screenshot_1.png
  Lists/Doubly Linked List/Images/Screenshot_2.png
  Lists/Doubly Linked List/README.md
  Lists/Doubly Linked List/doubly_linked_list.py
Labels: DCP21, To Do, 🟧 Level3

#107 Complex Number to Polar Coordinates
  Geometry/Complex To Polar Coordinates/Images/README.md
  Geometry/Complex To Polar Coordinates/Images/complexpolaroutput.png
  Geometry/Complex To Polar Coordinates/Images/complexpolaroutput1.png
  Geometry/Complex To Polar Coordinates/README.md
  Geometry/Complex To Polar Coordinates/complex_to_polar.py
  Geometry/README.md
Labels: DCP21, To Do, 🟩 Level1

#109 Binary Numbers
  Maths/Binary Numbers/Images/ss.png
  Maths/Binary Numbers/README.md
  Maths/Binary Numbers/binary_numbers.py
  Maths/README.md
Labels: DCP21, To Do, 🟩 Level1

#111 Mobile Price Range Classification #82
  Machine Learning/Mobile Price Range Classification/Dataset/train.csv
  Machine Learning/Mobile Price Range Classification/Images/lr1.jpg
  Machine Learning/Mobile Price Range Classification/Images/lr2.jpg
  Machine Learning/Mobile Price Range Classification/Images/lr3.jpg
  Machine Learning/Mobile Price Range Classification/Model/README.md
  Machine Learning/Mobile Price Range Classification/Model/mobile_price_range_classification.py
Labels: DCP21, To Do, 🟧 Level3

#114 Brute Forcing The Caesar Cipher
  Cryptography/Brute Forcing Caesar Cipher/Images/brute_force_output.png
  Cryptography/Brute Forcing Caesar Cipher/README.md
  Cryptography/Brute Forcing Caesar Cipher/brute_forcing_caesar_cipher.py
  Cryptography/README.md
Labels: DCP21, To Do, 🟩 Level1

#117 Quick Sort added
  Sorting/Quick Sort/Images/output1.png
  Sorting/Quick Sort/Images/output2.png
  Sorting/Quick Sort/README.md
  Sorting/Quick Sort/quick_sort.py
Labels: DCP21, To Do, 🟩 Level1

#121 Linked Queue
  Queues/Linked Queue/Images/Screenshot_1.png
  Queues/Linked Queue/Images/Screenshot_2.png
  Queues/Linked Queue/README.md
  Queues/Linked Queue/linked_queue.py
Labels: DCP21, To Do, 🟨 Level2

#119 Vigenere Cipher
  Ciphers/Vigenère Cipher/Images/Decryption Mode.png
  Ciphers/Vigenère Cipher/Images/Encryption Mode.png
  Ciphers/Vigenère Cipher/Images/Vignere Table.png
  Ciphers/Vigenère Cipher/README.md
  Ciphers/Vigenère Cipher/Vignere_Cipher.py
Labels: DCP21, To Do, 🟨 Level2

#122 Bitwise AND
  Maths/Bitwise AND/Images/ss.png
  Maths/Bitwise AND/README.md
  Maths/Bitwise AND/bitwise_AND.py
  Maths/README.md
Labels: DCP21, To Do, 🟩 Level1

#105 Array Operations
  Arrays/Array Operations/Images/Output1_part1.png
  Arrays/Array Operations/Images/Output1_part2.png
  Arrays/Array Operations/Images/Output1_part3.png
  Arrays/Array Operations/Images/Output1_part4.png
  Arrays/Array Operations/Images/Output1_part5.png
  Arrays/Array Operations/Images/Output1_part6.png
  Arrays/Array Operations/Images/Output1_part7.png
  Arrays/Array Operations/README.md
  Arrays/Array Operations/array_operations.py
  Arrays/Array Operations/requirements.txt
  Arrays/README.md
Labels: DCP21, To Do, 🟩 Level1

#125 BST Level Order Traversal
  Trees/BST Level Order Traversal/BST_level_order_traversal.py
  Trees/BST Level Order Traversal/Images/ss.png
  Trees/BST Level Order Traversal/README.md
  Trees/README.md
Labels: DCP21, To Do, 🟩 Level1

#131 Capitalizing
  Strings/Capitalizing/Images/ss.png
  Strings/Capitalizing/README.md
  Strings/Capitalizing/capitalizing.py
  Strings/README.md
Labels: DCP21, To Do, 🟪 Level0

#132 Depth First Search
  Searching/Depth First Search/Images/ss1.png
  Searching/Depth First Search/Images/ss2.png
  Searching/Depth First Search/README.md
  Searching/Depth First Search/depth_first_search.py
  Searching/README.md
Labels: DCP21, To Do, 🟨 Level2

#124 Shell Sort added
  Sorting/Shell Sort/Images/Output1.png
  Sorting/Shell Sort/Images/Output2.png
  Sorting/Shell Sort/README.md
  Sorting/Shell Sort/shell_sort.py
Labels: DCP21, To Do, 🟩 Level1
